config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :admins
  resources :dresses
  resources :weapons
  get 'weapons_type/:id' => 'types#index'
  get 'categories/:id' => 'categories#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  resources :users
  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :weapon
  belongs_to :dress
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/dress.rb
class Dress < ApplicationRecord
  has_many :categories
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attr_accessor  :search
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :weapon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  #User.commentsで、ユーザーの所有するコメントを取得できる。
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  
  mount_uploader :icon, ImageUploader
  
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :categories
  has_many :types
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def user_search(search)
    # @users = User.where(gender: search[:gender])
    # @users = @users.where(age: search[:min_age]..search[:max_age])
    # @users = 
  end
  
  
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/admins/index.html.erb
<h2>管理者ダッシュボード</h2>
<ul>
  <li><%= link_to "投稿管理", posts_path %></li>
  <li><%= link_to "ユーザー管理", "" %></li>
  <li><%= link_to "〇〇管理", "" %></li>
  <li><%= link_to "バ管理", "" %></li>

</ul>

app/views/layouts/_flash.html.erb
<div class="my-3">
  <% flash.each do |key, value| %>
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-3 bg-light">
  <div class="container">
    <span class="text-muted small">Simple Board by Ruby on Rails & Bootstrap 4</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'My App', root_path, class: "navbar-brand" %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      
      <!--// もしユーザーがログインしているならば下記を表示-->
      <%  if user_signed_in?  %>
        <%= render "layouts/users_login" %>
      <!--//ログインしていないのなら下記を表示-->
      <% else %>
        <%= render "layouts/users_logout" %>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_users_login.html.erb
<li class="nav-item">
  <span class="nav-link"><%= current_user.user_name %></span>
</li>
<li class="nav-item">
  <%= link_to edit_user_registration_path do %>
    <% if current_user.icon.present? %>
      <%= image_tag current_user.icon.url, class: "nav-icon nav-link" %>
    <% else %>
      <%= image_tag 'no_user_image.png', class: "nav-icon nav-link" %>
    <% end %>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to "Events", posts_path, class: "nav-link" %>
</li>
        
<!--<li class="nav-item dropdown">-->
<!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--  	ガチャ-->
<!--  </a>-->
<!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--    <%= link_to '武器ガチャ', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to '服装ガチャ', '#', class: 'dropdown-item' %>-->
<!--    <div class="dropdown-divider"></div>-->
<!--    <a class="dropdown-item" href="#">イベントガチャ</a>-->
<!--  </div>-->
<!--</li>-->
        
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  	装備
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to '武器一覧', weapons_path, class: 'dropdown-item' %>
    <%= link_to '服装一覧', dresses_path, class: 'dropdown-item' %>
  </div>
</li>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    装備追加
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to '武器追加', new_weapon_path, class: 'dropdown-item' %>
    <%= link_to '服装追加', new_dress_path, class: 'dropdown-item' %>
  </div>
</li>
        
<!--<li class="nav-item dropdown">-->
<!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--  	キャラクター-->
<!--  </a>-->
<!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--    <%= link_to 'キャラクター1', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター2', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター3', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター4', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター5', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター6', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター7', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター8', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター9', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター10', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター11', '#', class: 'dropdown-item' %>-->
<!--  </div>-->
<!--</li>-->
      
<li class="nav-item">
	<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/_users_logout.html.erb
<li class="nav-item">
  <%= link_to "Events", posts_path, class: "nav-link" %>
</li>
        
<!--<li class="nav-item dropdown">-->
<!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--  	ガチャ-->
<!--  </a>-->
<!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--    <%= link_to '武器ガチャ', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to '服装ガチャ', '#', class: 'dropdown-item' %>-->
<!--    <div class="dropdown-divider"></div>-->
<!--    <a class="dropdown-item" href="#">イベントガチャ</a>-->
<!--  </div>-->
<!--</li>-->
        
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  	装備
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to '武器一覧', weapons_path, class: 'dropdown-item' %>
    <%= link_to '服装一覧', dresses_path, class: 'dropdown-item' %>
  </div>
</li>
        
<!--<li class="nav-item dropdown">-->
<!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--  	キャラクター-->
<!--  </a>-->
<!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--    <%= link_to 'キャラクター1', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター2', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター3', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター4', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター5', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター6', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター7', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター8', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター9', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター10', '#', class: 'dropdown-item' %>-->
<!--    <%= link_to 'キャラクター11', '#', class: 'dropdown-item' %>-->
<!--  </div>-->
<!--</li>-->
      
<li class="nav-item">
  <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
</li>

<li class="nav-item">
  <%= link_to "有料会員になる", new_user_path, class: "nav-link" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SimpleBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div class="container-fruid h-100 p-2 d-flex flex-column">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
      <%= render "layouts/flash" %>
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main>
      <div class="container">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/views.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SimpleBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div class="container">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>