config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :admins
  resources :dresses
  resources :weapons
  get 'weapons_type/:id' => 'types#index'
  get 'categories/:id' => 'categories#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  resources :users
  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :weapon
  belongs_to :dress
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/dress.rb
class Dress < ApplicationRecord
  has_many :categories
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attr_accessor  :search
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :weapon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  #User.commentsで、ユーザーの所有するコメントを取得できる。
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  
  mount_uploader :icon, ImageUploader
  
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :categories
  has_many :types
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :post_search, only: [:index]

  # GET /posts
  # GET /posts.json
  def index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = current_user.comments.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id 

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
    
    
    def post_search
      if params[:search].present?
        @posts = Post.where("content LIKE ?", "%#{params[:search]}%")
      else
        @posts = Post.all
      end
      
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def user_search(search)
    # @users = User.where(gender: search[:gender])
    # @users = @users.where(age: search[:min_age]..search[:max_age])
    # @users = 
  end
  
  
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/posts/_comments.html.erb
<h2>コメントをする</h2>

<%= form_with(model:[@post, @comment], method: :post) do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <div class="field form-group">
    <%= f.label :comment_title %>
    <%= f.text_field :comment_title, class:"form-control" %>
  </div>
  
  <div class="field form-group">
    <%= f.label :comment_content %>
    <%= f.text_field :comment_content, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする", class: "btn btn-primary" %>
  </div>
<% end %>

<h2>コメント一覧</h2>

<% @comments.each do |comment| %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-0.5">
        <% if comment.user.icon.present? %>
          <%= image_tag comment.user.icon.url, class: "nav-icon nav-link" %>
        <% else %>
          <%= image_tag 'no_user_image.png', class: "nav-icon nav-link" %>
        <% end %>
      </div>
      <div class="col-11.5">
        <div class="card-body my-app-post-body">
          <h5 class="card-title"><%= comment.user.user_name %></h5>
          <h5 class="card-title"><%= comment.comment_title %></h5>
          <p class="card-text"><%= comment.comment_content %></p>
          <%= link_to 'Destroy', post_comment_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.comments.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= post.comments.title %></h5>
    <p class="card-text"><%= post.comments.content %></p>
    <% if request.path == "/post" %>
      <%= link_to 'Show', post.comments, class: "btn btn-outline-primary" %>
    <% end %>
    <%= link_to 'Edit', edit_post_comments_path(post.comments), class: "btn btn-outline-primary" %>
    <%= link_to 'Destroy', post_comments, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-0.5">
      <% if post.user.icon.present? %>
        <%= image_tag post.user.icon.url, class: "nav-icon nav-link" %>
      <% else %>
        <%= image_tag 'no_user_image.png', class: "nav-icon nav-link" %>
      <% end %>
    </div>
    <div class="col-11.5">
      <div class="card-body my-app-post-body">
        
        <h4 class="card-title font-weight-bold"><%= post.user.user_name %></h3>
        <h4 class="card-title font-weight-bold"><%= post.title %></h3>
        <p class="card-text"><%= post.content %></p>
        
        <% if user_signed_in? %>
          <% if post.favorited_by?(current_user) %> 
              <p><span><%= image_tag 'good.png', class: 'nice-btn' %></span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :delete %></p>
          <% else %>
              <p><span><%= image_tag 'no_good.png', class: 'nice-btn' %></span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :post %></p>
          <% end %>
        <% else %>
          <p><span>お気に入り数: </span><%= post.favorites.count %></p>
        <% end %>
        
        <% if request.path == "/posts" %>
          <%= link_to 'Show', post, class: "btn btn-outline-primary" %>
        <% end %>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary" %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<div>
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Events</h1>
<%= form_tag "/posts", method: "get" do  %>
  <%= text_field_tag :search %>
  <%= submit_tag "検索" %>
<% end %>

<%= render @posts %>

<div>
<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<div>
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>

<hr>
<%= render "posts/comments" %>

<%= link_to '>ホーム', root_path %>