config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :admins
  resources :dresses
  resources :weapons
  get 'weapons_type/:id' => 'types#index'
  get 'categories/:id' => 'categories#index'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  resources :users
  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :weapon
  belongs_to :dress
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/dress.rb
class Dress < ApplicationRecord
  has_many :categories
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  attr_accessor  :search
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :weapon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  #User.commentsで、ユーザーの所有するコメントを取得できる。
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  
  mount_uploader :icon, ImageUploader
  
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :categories
  has_many :types
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @category = params[:id]
    @weapons = Weapon.where(category: params[:id])
    @dresses = Dress.where(category: params[:id])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def user_search(search)
    # @users = User.where(gender: search[:gender])
    # @users = @users.where(age: search[:min_age]..search[:max_age])
    # @users = 
  end
  
  
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/categories/index.html.erb
<h1><%= @category %></h1>

<table class = "table text-center">
  <thead class = "thead-dark">
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Img</th>
      <th>Types</th>
      <th>Category</th>
      <th>Menu</th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.no %></td>
        <td><%= link_to weapon.name, weapon %></td>
        <td><%= weapon.img %></td>
        <td><%= link_to weapon.weapon_type, "/weapons_type/#{weapon.weapon_type}" %></td>
        <td><%= link_to weapon.category, "/categories/#{weapon.category}" %></td>
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_weapon_path(weapon), class: "btn btn-outline-primary" %> 
            <%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger"  %>
            <%= link_to 'Show', weapon_path(weapon), class: "btn btn-outline-primary" %>
          </td>
        <% else %>
          <td>
            <%= link_to 'Show', weapon_path(weapon), class: "btn btn-outline-primary" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<table class = "table text-center">
  <thead class = "thead-dark">
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Img</th>
      <th>Category</th>
      <th>Menu</th>
    </tr>
  </thead>

  <tbody>
    <% @dresses.each do |dress| %>
      <tr>
        <td><%= dress.no %></td>
        <td><%= link_to dress.name, dress %></td>
        <td><%= dress.img %></td>
        <td><%= link_to dress.category, "/categories/#{dress.category}" %></td>
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_dress_path(dress), class: "btn btn-outline-primary" %> 
            <%= link_to 'Destroy', dress, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger"  %>
            <%= link_to 'Show', dress_path(dress), class: "btn btn-outline-primary" %>
          </td>
        <% else %>
          <td>
            <%= link_to 'Show', dress_path(dress), class: "btn btn-outline-primary" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>